import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.58.0';

const SUPABASE_URL='https://bgtxfzvzksgvradodafo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable__rZ-ByelsWiRwQPTOEST4w_4u7TyFNe';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let channelId=null;

const $=(id)=>document.getElementById(id);
const fmt=(d)=>d?new Date(d).toLocaleString():'—';
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function status(el,msg,type=''){if(!el)return;el.textContent=msg;el.className=`status ${type}`;}
async function getSession(){const {data:{session}}=await supabase.auth.getSession();return session;}
async function ensureChannel(){const {data,error}=await supabase.rpc('ensure_hynoe_channel');if(error)throw error;channelId=data?.[0]?.channel_id||null;if(!channelId)throw new Error('Channel bootstrap failed');return channelId;}
async function hydrateClipUrls(rows){return Promise.all(rows.map(async c=>{if(!c.render_uri)return c;const {data,error}=await supabase.storage.from('clip-previews').createSignedUrl(c.render_uri,3600);return {...c,preview_url:error?null:data?.signedUrl};}));}
function showOAuthReturn(){const q=new URLSearchParams(location.search);const result=q.get('youtube');const detail=q.get('detail');if(!result)return;if(result==='connected')status($('oauth-save-status'),'@Hynoe connected successfully.','ok');else status($('oauth-save-status'),detail||'YouTube connection failed.','error');q.delete('youtube');q.delete('detail');history.replaceState(null,'',`${location.pathname}${q.toString()?`?${q}`:''}${location.hash}`);}

async function loadDashboard(){
  const session=await getSession();
  if(!session){$('auth-shell').classList.remove('hidden');$('dashboard').classList.add('hidden');return;}
  if(!session.user.email_confirmed_at){await supabase.auth.signOut();status($('auth-status'),'Verify your email before using the agent.','error');return;}
  $('auth-shell').classList.add('hidden');$('dashboard').classList.remove('hidden');
  await ensureChannel();
  const [jobsRes,clipsRes,pubsRes,analyticsRes,recsRes,connRes,configRes]=await Promise.all([
    supabase.from('processing_jobs').select('id,state,created_at,updated_at,error_message,video_sources(title,youtube_video_id,game_topic)').eq('channel_id',channelId).order('created_at',{ascending:false}).limit(30),
    supabase.from('clip_candidates').select('*').eq('channel_id',channelId).order('score',{ascending:false}).limit(30),
    supabase.from('publishing_jobs').select('id,state,created_at,youtube_video_id,clip_candidate_id,error_message').eq('channel_id',channelId).order('created_at',{ascending:false}).limit(50),
    supabase.from('analytics_snapshots').select('*').eq('channel_id',channelId).order('captured_at',{ascending:false}).limit(20),
    supabase.from('recommendations').select('*').eq('channel_id',channelId).eq('status','active').order('created_at',{ascending:false}).limit(20),
    supabase.from('youtube_connections').select('status,connected_at,last_error').eq('channel_id',channelId).maybeSingle(),
    supabase.functions.invoke('youtube-oauth-config',{body:{channel_id:channelId,action:'status'}})
  ]);
  [jobsRes,clipsRes,pubsRes,analyticsRes,recsRes].forEach(r=>{if(r.error)console.warn(r.error)});
  const clips=await hydrateClipUrls(clipsRes.data||[]);
  renderMetrics(jobsRes.data||[],clips,pubsRes.data||[]);renderJobs(jobsRes.data||[]);renderClips(clips,pubsRes.data||[]);renderAnalytics(analyticsRes.data||[]);renderRecommendations(recsRes.data||[]);
  const conn=connRes.data;
  $('youtube-connection').textContent=conn?.status==='connected'?`YouTube OAuth connected ${fmt(conn.connected_at)}`:conn?.last_error?`YouTube OAuth error: ${conn.last_error}`:'YouTube OAuth: not connected yet';
  $('connect-youtube-btn').textContent=conn?.status==='connected'?'Reconnect @Hynoe YouTube':'Connect @Hynoe YouTube';
  const cfg=configRes.data;
  status($('oauth-config-status'),cfg?.configured?`Google OAuth client saved (${cfg.client_id_hint||'configured'}).`:'Google OAuth client credentials still need to be saved.',cfg?.configured?'ok':'');
  if(cfg?.configured)$('oauth-setup').open=false;
  showOAuthReturn();
}

function renderMetrics(jobs,clips,pubs){$('metric-queued').textContent=jobs.filter(j=>['queued','claimed','downloading','transcribing','analyzing','rendering'].includes(j.state)).length;$('metric-review').textContent=clips.filter(c=>c.approval_state==='pending').length;$('metric-approved').textContent=clips.filter(c=>c.approval_state==='approved').length;$('metric-published').textContent=pubs.filter(p=>['published','uploaded_private'].includes(p.state)).length;}
function renderJobs(rows){const el=$('jobs');if(!rows.length){el.className='list empty';el.textContent='No jobs yet.';return;}el.className='list';el.innerHTML=rows.map(j=>`<div class="list-row"><div><strong>${esc(j.video_sources?.title||'Untitled')}</strong><div>${esc(j.video_sources?.game_topic||'No topic')} ${j.video_sources?.youtube_video_id?`• ${esc(j.video_sources.youtube_video_id)}`:''}</div></div><div><span class="badge ${j.state==='awaiting_review'?'warn':j.state==='completed'?'good':''}">${esc(j.state)}</span></div><div>${fmt(j.updated_at)}</div><div>${j.error_message?`<span title="${esc(j.error_message)}">⚠</span>`:''}</div></div>`).join('');}
function renderClips(rows,pubs){const el=$('clips');if(!rows.length){el.className='clip-grid empty';el.textContent='No clip candidates yet.';return;}const pubByClip=new Map(pubs.map(p=>[p.clip_candidate_id,p]));el.className='clip-grid';el.innerHTML=rows.map(c=>{const p=pubByClip.get(c.id);const publishedState=p?.state?` • ${esc(p.state)}`:'';return `<article class="clip-card">${c.preview_url?`<video controls playsinline src="${esc(c.preview_url)}"></video>`:''}<div class="body"><div class="clip-score">${c.score}<small>/100</small></div><span class="badge ${c.approval_state==='approved'?'good':c.approval_state==='pending'?'warn':''}">${esc(c.approval_state)}${publishedState}</span><h3>${esc(c.title||c.hook||'Untitled clip')}</h3><p>${esc(c.transcript_excerpt||'')}</p><p><strong>${esc(c.category)}</strong> • ${Math.round((c.end_ms-c.start_ms)/1000)}s</p><div class="clip-actions"><button data-approve="${c.id}">Approve & Upload Private</button><button class="secondary" data-edit="${c.id}">Edit</button><button class="reject" data-reject="${c.id}">Reject</button></div>${p?.error_message?`<p class="status error">${esc(p.error_message)}</p>`:''}</div></article>`;}).join('');el.querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',()=>reviewClip(b.dataset.approve,'approve')));el.querySelectorAll('[data-reject]').forEach(b=>b.addEventListener('click',()=>reviewClip(b.dataset.reject,'reject')));el.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editClip(b.dataset.edit,rows.find(r=>r.id===b.dataset.edit))));}
async function editClip(id,clip){const title=prompt('Short title',clip?.title||'');if(title===null)return;const description=prompt('Description',clip?.description||'');if(description===null)return;const {error}=await supabase.from('clip_candidates').update({title:title.trim(),description:description.trim(),updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return;}await loadDashboard();}
async function reviewClip(id,action){const {data,error}=await supabase.rpc('approve_clip',{p_clip_id:id,p_action:action,p_notes:null});if(error){alert(error.message);return;}if(action==='approve'){const pubId=data?.[0]?.publishing_job_id;if(pubId){const {data:upload,error:uploadErr}=await supabase.functions.invoke('youtube-upload-approved',{body:{publishing_job_id:pubId}});if(uploadErr||upload?.error)alert(`Clip approved. Private YouTube upload is still pending: ${upload?.error||uploadErr?.message||'connect YouTube first'}`);else alert(`Approved and uploaded privately to YouTube: ${upload.youtube_video_id}`);}}await loadDashboard();}
function renderAnalytics(rows){const el=$('analytics');if(!rows.length){el.className='list empty';el.textContent='No analytics yet.';return;}el.className='list';el.innerHTML=rows.map(a=>`<div class="list-row"><div><strong>${esc(a.youtube_video_id)}</strong><div>${esc(a.horizon)} snapshot</div></div><div>${Number(a.views||0).toLocaleString()} views</div><div>${a.average_percentage_viewed?`${Number(a.average_percentage_viewed).toFixed(1)}% avg viewed`:'—'}</div><div>${fmt(a.captured_at)}</div></div>`).join('');}
function renderRecommendations(rows){const el=$('recommendations');if(!rows.length){el.className='list empty';el.textContent='Not enough data yet.';return;}el.className='list';el.innerHTML=rows.map(r=>`<div class="list-row"><div><strong>${esc(r.title)}</strong><div>${esc(r.body)}</div></div><div><span class="badge">${esc(r.recommendation_type)}</span></div><div>${esc(r.confidence)} confidence</div><div>${fmt(r.created_at)}</div></div>`).join('');}

$('login-form').addEventListener('submit',async(e)=>{e.preventDefault();status($('auth-status'),'Signing in…');const email=$('email').value.trim(),password=$('password').value;const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){status($('auth-status'),error.message,'error');return;}if(!data.user?.email_confirmed_at){await supabase.auth.signOut();status($('auth-status'),'Verify your email first.','error');return;}status($('auth-status'),'Signed in.','ok');await loadDashboard();});
$('signup-btn').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8){status($('auth-status'),'Enter your email and an 8+ character password first.','error');return;}status($('auth-status'),'Creating account…');const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});status($('auth-status'),error?error.message:'Account created. Check your email to verify it.',error?'error':'ok');});
$('vod-form').addEventListener('submit',async(e)=>{e.preventDefault();if(!channelId)return;status($('vod-status'),'Queueing…');const title=$('vod-title').value.trim(),youtubeId=$('vod-id').value.trim()||null,topic=$('vod-topic').value.trim()||null;const {data,error}=await supabase.rpc('enqueue_video_source',{p_channel_id:channelId,p_youtube_video_id:youtubeId,p_source_type:youtubeId?'youtube':'manual',p_title:title,p_duration_seconds:null,p_game_topic:topic});if(error){status($('vod-status'),error.message,'error');return;}status($('vod-status'),data?.[0]?.created?'Queued for processing.':'Already queued; duplicate avoided.','ok');e.target.reset();await loadDashboard();});
$('save-oauth-btn').addEventListener('click',async()=>{if(!channelId)return;const clientId=$('youtube-client-id').value.trim(),clientSecret=$('youtube-client-secret').value.trim();if(!clientId||!clientSecret){status($('oauth-save-status'),'Paste both the Google Client ID and Client Secret.','error');return;}status($('oauth-save-status'),'Encrypting and saving…');const {data,error}=await supabase.functions.invoke('youtube-oauth-config',{body:{channel_id:channelId,client_id:clientId,client_secret:clientSecret}});$('youtube-client-secret').value='';if(error||data?.error){status($('oauth-save-status'),data?.error||error?.message||'Could not save credentials.','error');return;}status($('oauth-save-status'),'Saved securely in Supabase Vault. Now click Connect @Hynoe YouTube.','ok');await loadDashboard();});
$('copy-callback-btn').addEventListener('click',async()=>{await navigator.clipboard.writeText($('oauth-callback').value);status($('oauth-save-status'),'Redirect URI copied.','ok');});
$('connect-youtube-btn').addEventListener('click',async()=>{const {data,error}=await supabase.functions.invoke('youtube-oauth-start',{body:{channel_id:channelId,return_to:location.origin}});if(error||data?.error){alert(data?.error||`YouTube connection is not configured yet: ${error?.message||'unknown error'}`);$('oauth-setup').open=true;return;}if(data?.url)location.href=data.url;else alert('YouTube OAuth did not return a URL.');});
$('sync-analytics-btn').addEventListener('click',async()=>{const btn=$('sync-analytics-btn');btn.disabled=true;btn.textContent='Syncing…';const {data,error}=await supabase.functions.invoke('youtube-analytics-sync',{body:{channel_id:channelId}});btn.disabled=false;btn.textContent='Sync';if(error||data?.error)alert(data?.error||error?.message);else{alert(`Analytics synced: ${data.inserted||0} snapshots added.`);await loadDashboard();}});
$('logout-btn').addEventListener('click',async()=>{await supabase.auth.signOut();channelId=null;await loadDashboard();});$('refresh-btn').addEventListener('click',loadDashboard);supabase.auth.onAuthStateChange(()=>setTimeout(loadDashboard,0));loadDashboard().catch(err=>{console.error(err);status($('auth-status'),err.message,'error')});
