import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.58.0';
const s=createClient('https://bgtxfzvzksgvradodafo.supabase.co','sb_publishable__rZ-ByelsWiRwQPTOEST4w_4u7TyFNe');
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let channel,rows=[],state='ready';
async function readCatalog(){const rows=[];for(let offset=0;;offset+=1000){const r=await s.from('revival_catalog').select('*').eq('channel_id',channel).order('video_id').range(offset,offset+999);if(r.error)return r;rows.push(...r.data);if(r.data.length<1000)return{data:rows,error:null};}}
function render(){const selected=rows.filter(r=>r.state===state||(state==='ready'&&r.state==='processing'));$('queue').innerHTML=selected.length?selected.map(r=>`<article class="queue-card"><span>${esc(r.state)} · Rank ${r.rank} · ${esc(r.score)}/100</span><h3>${esc(r.target_title)}</h3><p>${esc(r.reason)}</p><p class="muted">${r.analytics_complete?'Numeric analytics present':'Awaiting canonical analytics'}${Number(r.score)<90?' · Below automatic 90 threshold':''}${r.last_error?' · '+esc(r.last_error):''}</p><details><summary>Exact revival package</summary><label>Title</label><p>${esc(r.target_title)}</p><label>Description</label><pre>${esc(r.target_description)}</pre><label>Playlist</label><p>${esc(r.target_playlist)}</p><label>Historical evidence</label><pre>${esc(JSON.stringify(r.historical,null,2))}</pre><a href="https://www.youtube.com/watch?v=${encodeURIComponent(r.video_id)}" target="_blank" rel="noreferrer">Open video</a></details></article>`).join(''):'<p>No items in this state.</p>';}
async function load(){
 const {data:{session}}=await s.auth.getSession();if(!session){$('status').textContent='Sign in on the main Agent first.';$('sync').disabled=$('run').disabled=true;return;}
 const {data,error}=await s.rpc('ensure_hynoe_channel');if(error)throw error;channel=data?.[0]?.channel_id;
 const responses=await Promise.all([s.from('revival_queue').select('*').eq('channel_id',channel).order('rank'),s.from('revival_control').select('*').eq('channel_id',channel).single(),readCatalog(),s.from('revival_sync').select('*').eq('channel_id',channel).maybeSingle()]);
 for(const r of responses)if(r.error)throw r.error;
 rows=responses[0].data;const ctl=responses[1].data,catalog=responses[2].data,sync=responses[3].data;
 const paused=ctl.pause_until&&Date.parse(ctl.pause_until)>Date.now();
 $('status').textContent=paused?`YouTube quota paused until ${new Date(ctl.pause_until).toLocaleString()}. Queue preparation remains available.`:`${ctl.catalog_complete?'Catalog enumeration complete':'Catalog sync incomplete'}. ${ctl.catalog_count_discrepancy?'Current owner count differs from the historical 882. ':''}${sync?.last_error||''}`;
 $('sync').disabled=$('run').disabled=!!paused;
 $('metrics').innerHTML=[['Catalog coverage',`${catalog.length} / ${ctl.observed_catalog_count??ctl.expected_catalog_count}`],['Numeric analytics',catalog.filter(x=>x.analytics_complete).length],['Prior approved ready',rows.filter(x=>x.state==='ready').length],['Deferred',rows.filter(x=>x.state==='deferred').length]].map(([label,value])=>`<article class="card metric"><strong>${esc(value)}</strong>${esc(label)}</article>`).join('');
 const sorted=[...catalog].sort((a,b)=>Number(b.evidence.watch_minutes||0)-Number(a.evidence.watch_minutes||0));
 $('watch').innerHTML=sorted.length?sorted.map(r=>`<tr><td>${esc(r.title)}</td><td>${esc(r.privacy)}</td><td>${r.evidence.watch_minutes==null?'Unknown':(r.evidence.watch_minutes/60).toFixed(1)}</td><td>${r.evidence.avg_viewed_pct==null?'Unknown':r.evidence.avg_viewed_pct.toFixed(1)+'%'}</td><td>${r.score==null?'Unknown':esc(r.score)}</td><td>${esc(r.decision)}</td></tr>`).join(''):'<tr><td colspan="6">Canonical owner catalog has not synced yet. No analytics are fabricated.</td></tr>';
 render();
}
async function invoke(name){if(!channel)return;const buttons=[$('sync'),$('run')];buttons.forEach(b=>b.disabled=true);try{const{data,error}=await s.functions.invoke(name,{body:{channel_id:channel}});if(error||data?.error)throw Error(data?.error||error.message);await load();$('status').textContent=data.paused?`Paused until ${new Date(data.resume_at).toLocaleString()}`:JSON.stringify(data);}catch(e){$('status').textContent=e.message;buttons.forEach(b=>b.disabled=false);}}
document.querySelectorAll('[data-state]').forEach(b=>b.addEventListener('click',()=>{state=b.dataset.state;document.querySelectorAll('[data-state]').forEach(x=>x.classList.toggle('active',x===b));render();}));
$('refresh').addEventListener('click',()=>load().catch(e=>$('status').textContent=e.message));$('sync').addEventListener('click',()=>invoke('youtube-revival-catalog-sync'));$('run').addEventListener('click',()=>invoke('youtube-archive-revive'));load().catch(e=>$('status').textContent=e.message);
