begin;
do $$declare ch uuid; v text; t uuid; n int; ok boolean;
begin
 select id into ch from public.channels where youtube_channel_id='UCjWR1CZVFkrVk3S-TRrOGGQ';
 if has_function_privilege('authenticated','public.claim_revival(uuid,text)','execute') or has_function_privilege('anon','public.claim_revival(uuid,text)','execute') then raise exception 'claim exposed';end if;
 if has_table_privilege('authenticated','public.revival_queue','update') then raise exception 'queue writable by browser';end if;
 select video_id into v from public.revival_queue where channel_id=ch and rank=1;
 update public.revival_control set pause_until=null,catalog_complete=true,last_publication_at=null where channel_id=ch;
 update public.revival_queue set state='ready',score=95,analytics_complete=true where channel_id=ch and video_id=v;
 insert into public.revival_catalog(channel_id,video_id,title,score,analytics_complete,decision,evidence) values(ch,v,'rollback fixture',95,true,'wave-1','{"score_version":"numeric-v1"}') on conflict(channel_id,video_id) do update set score=95,analytics_complete=true,evidence='{"score_version":"numeric-v1"}';
 update public.revival_catalog set duration_seconds=30 where channel_id=ch and video_id=v;
 select count(*) into n from public.claim_revival(ch,v);if n<>0 then raise exception 'short entered long-form revival';end if;
 update public.revival_catalog set duration_seconds=3600,evidence=evidence||'{"editorial_fit":true}' where channel_id=ch and video_id=v;
 select lease_token into t from public.claim_revival(ch,v);if t is null then raise exception 'claim failed';end if;
 select public.reserve_revival_publication(ch,v,t) into ok;if not ok then raise exception 'publication reservation failed';end if;
 select count(*) into n from public.claim_revival(ch,v);if n<>0 then raise exception 'duplicate claim';end if;
 select public.finish_revival(ch,v,gen_random_uuid(),'published') into ok;if ok then raise exception 'stale worker finalized';end if;
 select public.finish_revival(ch,v,t,'quota','quotaExceeded') into ok;if not ok then raise exception 'quota did not persist';end if;
 select count(*) into n from public.claim_revival(ch,v);if n<>0 then raise exception 'quota pause ignored';end if;
 update public.revival_control set pause_until=null where channel_id=ch;
 update public.revival_queue set publication_started_at=now()-interval '48 hours' where channel_id=ch and video_id=v;
 update public.revival_control set last_publication_at=now() where channel_id=ch;
 select lease_token into t from public.claim_revival(ch,v);
 select public.reserve_revival_publication(ch,v,t) into ok;if ok then raise exception 'old reservation bypassed daily cap';end if;
 update public.revival_queue set state='ready',lease_until=null where channel_id=ch and video_id=v;
 update public.revival_control set last_publication_at=null where channel_id=ch;
 select lease_token into t from public.claim_revival(ch,v);
 select public.finish_revival(ch,v,t,'published') into ok;if not ok then raise exception 'completion failed';end if;
 select count(*) into n from public.claim_revival(ch,null);if n<>0 then raise exception 'daily cap ignored';end if;
 select lease_token into t from public.claim_catalog_sync(ch);
 select public.finish_catalog_sync(ch,t,'rollback-uploads',null,true,1) into ok;
 if not ok or not (select catalog_complete from public.revival_control where channel_id=ch) then raise exception 'exhausted catalog blocked by historical count';end if;
end $$;
rollback;
